#!/bin/sh
for f in  \
./pom.xml \
./src/main/java/com/epi/AddingCredits.java \
./src/main/java/com/epi/AddTwoNumberList.java \
./src/main/java/com/epi/Anagrams.java \
./src/main/java/com/epi/AnonymousLetter.java \
./src/main/java/com/epi/ApproximateSort.java \
./src/main/java/com/epi/Arbitrage.java \
./src/main/java/com/epi/AverageTop3Scores.java \
./src/main/java/com/epi/BalancedBinaryTreeTemplate.java \
./src/main/java/com/epi/Bentleybsearch.java \
./src/main/java/com/epi/BiggestProductNMinus1.java \
./src/main/java/com/epi/BiggestProductNMinus1Math.java \
./src/main/java/com/epi/BigNumberMultiplication.java \
./src/main/java/com/epi/BinaryOperator.java \
./src/main/java/com/epi/BinarySearchAiEqI.java \
./src/main/java/com/epi/BinarySearchCircularArrayTemplate.java \
./src/main/java/com/epi/BinarySearchCircularArrayWithDuplicatesTemplate.java \
./src/main/java/com/epi/BinarySearchFirstKTemplate.java \
./src/main/java/com/epi/BinarySearchLargerKTemplate.java \
./src/main/java/com/epi/BinarySearchTree.java \
./src/main/java/com/epi/BinarySearchUnknownLengthTemplate.java \
./src/main/java/com/epi/BinaryTreeLevelOrderTemplate.java \
./src/main/java/com/epi/BinaryTreeLockTemplate.java \
./src/main/java/com/epi/BinaryTreePostorderTraversalIterative.java \
./src/main/java/com/epi/BinaryTreePostorderTraversalIterativeAlternative.java \
./src/main/java/com/epi/BinaryTreePreorderTraversalIterative.java \
./src/main/java/com/epi/BinaryTreePrototypeTemplate.java \
./src/main/java/com/epi/BinaryTreeUtils.java \
./src/main/java/com/epi/BinaryTreeWithParentPrototype.java \
./src/main/java/com/epi/Bonus.java \
./src/main/java/com/epi/BonusImproved.java \
./src/main/java/com/epi/BSTLowestCommonAncestor.java \
./src/main/java/com/epi/BSTSortedOrderTemplate.java \
./src/main/java/com/epi/BSTToSortedDoublyList.java \
./src/main/java/com/epi/BuildBSTFromSortedArray.java \
./src/main/java/com/epi/CanStringBePalindrome.java \
./src/main/java/com/epi/CanStringBePalindromeHash.java \
./src/main/java/com/epi/CanStringBePalindromeSorting.java \
./src/main/java/com/epi/CelebrityFinding.java \
./src/main/java/com/epi/CheckingCycle.java \
./src/main/java/com/epi/CheckingCycleAlternative.java \
./src/main/java/com/epi/CircularQueueTemplate.java \
./src/main/java/com/epi/CloneGraph.java \
./src/main/java/com/epi/CloseSearch.java \
./src/main/java/com/epi/ClosestIntSameBits.java \
./src/main/java/com/epi/ClosestPairPoints.java \
./src/main/java/com/epi/ClosestPalindrome.java \
./src/main/java/com/epi/ClosestStars.java \
./src/main/java/com/epi/ClosestToMedian.java \
./src/main/java/com/epi/CollatzConjecture.java \
./src/main/java/com/epi/Combinations.java \
./src/main/java/com/epi/CompareKthLargestInHeap.java \
./src/main/java/com/epi/CompletionSearch.java \
./src/main/java/com/epi/ComputingBinomialCoefficients.java \
./src/main/java/com/epi/ComputingXPowN.java \
./src/main/java/com/epi/ConnectLeavesBinaryTreeTemplate.java \
./src/main/java/com/epi/ContainerWithMostWater.java \
./src/main/java/com/epi/ConvertBase.java \
./src/main/java/com/epi/CopyingPostingsList.java \
./src/main/java/com/epi/CountingSort.java \
./src/main/java/com/epi/CountInversions.java \
./src/main/java/com/epi/CountOccurrencesInSentence.java \
./src/main/java/com/epi/CyclicRightShift.java \
./src/main/java/com/epi/DeletionListTemplate.java \
./src/main/java/com/epi/DescendantAndAncestor.java \
./src/main/java/com/epi/Division.java \
./src/main/java/com/epi/Doors.java \
./src/main/java/com/epi/DoublyLinkedListPrototypeTemplate.java \
./src/main/java/com/epi/DrawingSkylines.java \
./src/main/java/com/epi/DutchNationalFlag.java \
./src/main/java/com/epi/EliasCoding.java \
./src/main/java/com/epi/EliminateDuplicate.java \
./src/main/java/com/epi/EquivClasses.java \
./src/main/java/com/epi/EvenOddMergeLinkedListTemplate.java \
./src/main/java/com/epi/ExteriorBinaryTreeTemplate.java \
./src/main/java/com/epi/FindElementAppearsOnce.java \
./src/main/java/com/epi/FindingMinMax.java \
./src/main/java/com/epi/FindKLargestBST.java \
./src/main/java/com/epi/FindKthElementInTwoSortedArraysTemplate.java \
./src/main/java/com/epi/FindMissingAndDuplicate.java \
./src/main/java/com/epi/FindMissingAndDuplicateXOR.java \
./src/main/java/com/epi/FirstMissingPositive.java \
./src/main/java/com/epi/GassingUp.java \
./src/main/java/com/epi/GaussianElimination.java \
./src/main/java/com/epi/GaussianPrimes.java \
./src/main/java/com/epi/GCD.java \
./src/main/java/com/epi/GenerateParentheses.java \
./src/main/java/com/epi/GeneratingABSqrt2.java \
./src/main/java/com/epi/GeneratingABSqrt2Improved.java \
./src/main/java/com/epi/GrayCode.java \
./src/main/java/com/epi/HashDictionary.java \
./src/main/java/com/epi/HeightDetermination.java \
./src/main/java/com/epi/HighestAffinityPairs.java \
./src/main/java/com/epi/HouseMajority.java \
./src/main/java/com/epi/HuffmanEncoding.java \
./src/main/java/com/epi/ImageCompression.java \
./src/main/java/com/epi/IndirectSort.java \
./src/main/java/com/epi/InorderTraversalNoStackTemplate.java \
./src/main/java/com/epi/InorderTraversalWithParentTemplate.java \
./src/main/java/com/epi/InsertInterval.java \
./src/main/java/com/epi/InsertionSortList.java \
./src/main/java/com/epi/InterconvertingStringInteger.java \
./src/main/java/com/epi/InterleavingString.java \
./src/main/java/com/epi/IntersectRectangle.java \
./src/main/java/com/epi/IntersectSortedArrays.java \
./src/main/java/com/epi/IntersectSortedArrays1.java \
./src/main/java/com/epi/IntersectSortedArrays2.java \
./src/main/java/com/epi/IntersectSortedArrays3.java \
./src/main/java/com/epi/IsBinaryTreeABST.java \
./src/main/java/com/epi/IsBinaryTreeAbstBfs.java \
./src/main/java/com/epi/IsBinaryTreeABSTConstSpace.java \
./src/main/java/com/epi/JobAssignment.java \
./src/main/java/com/epi/JumpGame.java \
./src/main/java/com/epi/KBalancedBinaryTreeTemplate.java \
./src/main/java/com/epi/KthElementStreaming.java \
./src/main/java/com/epi/KThLargestElement.java \
./src/main/java/com/epi/KthLargestElementLargeN.java \
./src/main/java/com/epi/KthLargestElementTemplate.java \
./src/main/java/com/epi/KThNodeBinaryTree.java \
./src/main/java/com/epi/KThNodeBinaryTreeTemplate.java \
./src/main/java/com/epi/LargeArray.java \
./src/main/java/com/epi/LargestRectangleUnderSkyline.java \
./src/main/java/com/epi/LazyInit.java \
./src/main/java/com/epi/LeftJustifiedText.java \
./src/main/java/com/epi/LevenshteinDistance.java \
./src/main/java/com/epi/LineMostPoints.java \
./src/main/java/com/epi/LinkedList.java \
./src/main/java/com/epi/LinkedListPrototypeTemplate.java \
./src/main/java/com/epi/ListPivoting.java \
./src/main/java/com/epi/LoadBalancing.java \
./src/main/java/com/epi/LongestContainedRange.java \
./src/main/java/com/epi/LongestIncreasingSubarray.java \
./src/main/java/com/epi/LongestNondecreasingSubsequenceN2.java \
./src/main/java/com/epi/LongestNondecreasingSubsequenceNlogn.java \
./src/main/java/com/epi/LongestSubarrayK.java \
./src/main/java/com/epi/LongestSubarrayWithDistinctEntries.java \
./src/main/java/com/epi/LongestValidParentheses.java \
./src/main/java/com/epi/LookAndSay.java \
./src/main/java/com/epi/LowestCommonAncestorHashTemplate.java \
./src/main/java/com/epi/LowestCommonAncestorNoParentTemplate.java \
./src/main/java/com/epi/LowestCommonAncestorTemplate.java \
./src/main/java/com/epi/LRUCache.java \
./src/main/java/com/epi/MatrixRotation.java \
./src/main/java/com/epi/MatrixRotationConstant.java \
./src/main/java/com/epi/MatrixRotationNaive.java \
./src/main/java/com/epi/MatrixSearch.java \
./src/main/java/com/epi/MaxDifferenceKPairs.java \
./src/main/java/com/epi/MaxDifferenceUnlimitedPairs.java \
./src/main/java/com/epi/MaximumSubarrayInCircularArray.java \
./src/main/java/com/epi/MaximumSubarrayInCircularArrayConstantSpace.java \
./src/main/java/com/epi/MaxSubmatrixRectangle.java \
./src/main/java/com/epi/MaxSubmatrixRectangleBruteForce.java \
./src/main/java/com/epi/MaxSubmatrixRectangleImproved.java \
./src/main/java/com/epi/MaxSubmatrixSquare.java \
./src/main/java/com/epi/MaxSumSubarray.java \
./src/main/java/com/epi/MedianSortedCircularLinkedListTemplate.java \
./src/main/java/com/epi/MergeSortedArrays.java \
./src/main/java/com/epi/MergeSortedListsTemplate.java \
./src/main/java/com/epi/MergeTwoBSTs.java \
./src/main/java/com/epi/MergeTwoSortedArraysInPlace.java \
./src/main/java/com/epi/MinimumDistance3SortedArrays.java \
./src/main/java/com/epi/MinimumSubarrayDifference.java \
./src/main/java/com/epi/MinimumWaitingTime.java \
./src/main/java/com/epi/MissingElement.java \
./src/main/java/com/epi/MultibetCardColorGame.java \
./src/main/java/com/epi/MultiplyShiftAdd.java \
./src/main/java/com/epi/NearestRepetition.java \
./src/main/java/com/epi/NearestRestaurant.java \
./src/main/java/com/epi/NextPermutation.java \
./src/main/java/com/epi/NodeT.java \
./src/main/java/com/epi/NonUniformRandomNumberGeneration.java \
./src/main/java/com/epi/NormalizedPathnames.java \
./src/main/java/com/epi/NQueens.java \
./src/main/java/com/epi/NumberSteps.java \
./src/main/java/com/epi/NumberWays.java \
./src/main/java/com/epi/NumberWaysObstacles.java \
./src/main/java/com/epi/OfflineMinimum.java \
./src/main/java/com/epi/OfflineSampling.java \
./src/main/java/com/epi/OnlineMedian.java \
./src/main/java/com/epi/OnlineSampling.java \
./src/main/java/com/epi/OverlappingListsNoCycle.java \
./src/main/java/com/epi/OverlappingListsTemplate.java \
./src/main/java/com/epi/PaintingIterative.java \
./src/main/java/com/epi/PaintingRecursive.java \
./src/main/java/com/epi/PalindromeLinkedListTemplate.java \
./src/main/java/com/epi/PalindromeNumber.java \
./src/main/java/com/epi/PalindromePartitioning.java \
./src/main/java/com/epi/PalindromePartitioningMinCuts.java \
./src/main/java/com/epi/Parity.java \
./src/main/java/com/epi/Parity1.java \
./src/main/java/com/epi/Parity2.java \
./src/main/java/com/epi/Parity3.java \
./src/main/java/com/epi/Parity4.java \
./src/main/java/com/epi/PascalTriangle1.java \
./src/main/java/com/epi/PathSumBinaryTree.java \
./src/main/java/com/epi/PermutationArray.java \
./src/main/java/com/epi/PermutationArray1.java \
./src/main/java/com/epi/PermutationArray2.java \
./src/main/java/com/epi/PermutationsAlternative.java \
./src/main/java/com/epi/PhoneMnemonic.java \
./src/main/java/com/epi/PickingUpCoins.java \
./src/main/java/com/epi/PickingUpCoinsDontLose.java \
./src/main/java/com/epi/PlanningFishing.java \
./src/main/java/com/epi/PlusOne.java \
./src/main/java/com/epi/PointsCoveringIntervals.java \
./src/main/java/com/epi/PointsCoveringIntervalsAlternative.java \
./src/main/java/com/epi/PopulatingNextRightPointers.java \
./src/main/java/com/epi/PostingListNode.java \
./src/main/java/com/epi/PostingsListPrototype.java \
./src/main/java/com/epi/PowerSet.java \
./src/main/java/com/epi/PowerSetAlternative.java \
./src/main/java/com/epi/PowerXY.java \
./src/main/java/com/epi/PrettyPrinting.java \
./src/main/java/com/epi/PrimeSieve.java \
./src/main/java/com/epi/QueueFromStacksTemplate.java \
./src/main/java/com/epi/QueueUsingTwoIntegers.java \
./src/main/java/com/epi/QueueWithMax.java \
./src/main/java/com/epi/QueueWithMaxUsingDeque.java \
./src/main/java/com/epi/Rearrange.java \
./src/main/java/com/epi/RebuildBSTPostorder.java \
./src/main/java/com/epi/RebuildBSTPreorder.java \
./src/main/java/com/epi/RebuildBSTPreorderBetter.java \
./src/main/java/com/epi/ReconstructAlmostBst.java \
./src/main/java/com/epi/ReconstructBinaryTreePostInOrdersTemplate.java \
./src/main/java/com/epi/ReconstructBinaryTreePreInOrdersTemplate.java \
./src/main/java/com/epi/ReconstructPreorderWithNullTemplate.java \
./src/main/java/com/epi/RegularExpression.java \
./src/main/java/com/epi/RemoveDuplicatesFromSortedArray.java \
./src/main/java/com/epi/RemoveDuplicatesSortedList.java \
./src/main/java/com/epi/RemoveElement.java \
./src/main/java/com/epi/RemoveKthLastListTemplate.java \
./src/main/java/com/epi/RenderingCalendar.java \
./src/main/java/com/epi/ReplaceAndRemove.java \
./src/main/java/com/epi/ReservoirSampling.java \
./src/main/java/com/epi/ReverseBits.java \
./src/main/java/com/epi/ReverseInteger.java \
./src/main/java/com/epi/ReverseLinkedListIterativeTemplate.java \
./src/main/java/com/epi/ReverseLinkedListRecursiveTemplate.java \
./src/main/java/com/epi/ReverseLinkListFromSToF.java \
./src/main/java/com/epi/ReverseListInKGroup.java \
./src/main/java/com/epi/ReverseWords.java \
./src/main/java/com/epi/RoadNetwork.java \
./src/main/java/com/epi/RobotBattery.java \
./src/main/java/com/epi/RomanToInteger.java \
./src/main/java/com/epi/RookAttack.java \
./src/main/java/com/epi/RotateArray.java \
./src/main/java/com/epi/RotateArrayPermutation.java \
./src/main/java/com/epi/RotateArrayTest.java \
./src/main/java/com/epi/RPN.java \
./src/main/java/com/epi/RunLengthCompression.java \
./src/main/java/com/epi/ScoreCombination.java \
./src/main/java/com/epi/ScorePermutation.java \
./src/main/java/com/epi/SearchAPairSortedArrayTemplate.java \
./src/main/java/com/epi/SearchBSTFirstLargerK.java \
./src/main/java/com/epi/SearchBSTForFirstOccurrenceIterative.java \
./src/main/java/com/epi/SearchBSTForFirstOccurrenceRecursive.java \
./src/main/java/com/epi/SearchFrequentItems.java \
./src/main/java/com/epi/SearchMajority.java \
./src/main/java/com/epi/SearchMaze.java \
./src/main/java/com/epi/SearchMinFirstBST.java \
./src/main/java/com/epi/SearchPostingsListIterative.java \
./src/main/java/com/epi/SearchPostingsListRecursive.java \
./src/main/java/com/epi/ShortestPathFewestEdges.java \
./src/main/java/com/epi/ShortestUniquePrefix.java \
./src/main/java/com/epi/SlidingWindow.java \
./src/main/java/com/epi/SmallestSubarrayCoveringSet.java \
./src/main/java/com/epi/SmallestSubarrayCoveringSetStream.java \
./src/main/java/com/epi/SnakeString.java \
./src/main/java/com/epi/SortedListToBST.java \
./src/main/java/com/epi/SortList.java \
./src/main/java/com/epi/SpiralMatrix.java \
./src/main/java/com/epi/SpiralMatrixClockwise.java \
./src/main/java/com/epi/SpreadsheetEncoding.java \
./src/main/java/com/epi/SquareRoot.java \
./src/main/java/com/epi/SquareRootInt.java \
./src/main/java/com/epi/StableAssignment.java \
./src/main/java/com/epi/StackQueueUsingHeapTemplate.java \
./src/main/java/com/epi/StackSorting.java \
./src/main/java/com/epi/StackWithMaxImproved.java \
./src/main/java/com/epi/StackWithMaxTemplate.java \
./src/main/java/com/epi/StringInMatrix.java \
./src/main/java/com/epi/SubseqCover.java \
./src/main/java/com/epi/SubstringWithConcatenationOfAllWords.java \
./src/main/java/com/epi/Successor.java \
./src/main/java/com/epi/SudokuCheck.java \
./src/main/java/com/epi/SudokuSolve.java \
./src/main/java/com/epi/SumRootToLeafBinaryTree.java \
./src/main/java/com/epi/SurroundedRegions.java \
./src/main/java/com/epi/SwapBits.java \
./src/main/java/com/epi/SymmetricBinaryTreeTemplate.java \
./src/main/java/com/epi/Tail.java \
./src/main/java/com/epi/TailCoin.java \
./src/main/java/com/epi/TaskAssignment.java \
./src/main/java/com/epi/TeamPhoto1.java \
./src/main/java/com/epi/TeamPhoto2.java \
./src/main/java/com/epi/TheoryOfEquality.java \
./src/main/java/com/epi/ThreeJugs.java \
./src/main/java/com/epi/ThreeSum.java \
./src/main/java/com/epi/TiesElection.java \
./src/main/java/com/epi/TournamentTree.java \
./src/main/java/com/epi/TowerHanoi.java \
./src/main/java/com/epi/TransformStringToOther.java \
./src/main/java/com/epi/TransitiveClosure.java \
./src/main/java/com/epi/TrappingRainWater.java \
./src/main/java/com/epi/TreeDiameter.java \
./src/main/java/com/epi/Triangle.java \
./src/main/java/com/epi/TwoExists.java \
./src/main/java/com/epi/TwoForAll.java \
./src/main/java/com/epi/UnconstructableChange.java \
./src/main/java/com/epi/UniformRandomNumberGeneration.java \
./src/main/java/com/epi/UnionIntervals.java \
./src/main/java/com/epi/UniqueBinaryTreesAll.java \
./src/main/java/com/epi/UpdateBST.java \
./src/main/java/com/epi/ValidIPAddress.java \
./src/main/java/com/epi/ValidPalindrome.java \
./src/main/java/com/epi/ValidParentheses.java \
./src/main/java/com/epi/ViewFromAbove.java \
./src/main/java/com/epi/ViewSunset.java \
./src/main/java/com/epi/WiringCircuitBoard.java \
./src/main/java/com/epi/WordBreaking.java \
./src/main/java/com/epi/ZeroOneKnapsack.java \
./src/main/java/com/epi/ZeroSumSubset.java \
./src/main/java/com/epi/ZippingListTemplate.java \
./src/main/resources/configurations/EpiCheckstyleConfig.xml \
./src/main/resources/configurations/EpiEclipseProfile.xml
do
  echo "processing $f"
  cp $f ~/epibook.github.io/solutions/java/src/main/java/com/epi/
done

for f in  \
./src/main/java/com/epi/utils/BinaryOperator.java \
./src/main/java/com/epi/utils/BinaryOperators.java \
./src/main/java/com/epi/utils/EndPoint.java \
./src/main/java/com/epi/utils/Interval.java \
./src/main/java/com/epi/utils/Pair.java \
./src/main/java/com/epi/utils/Ref.java \
./src/main/java/com/epi/utils/Utils.java 
do
  echo "processing $f"
  cp $f ~/epibook.github.io/solutions/java/src/main/java/com/epi/utils/
done

