cp ~/epi/java/PalindromeNumber.java .
cp ~/epi/java/RemoveDuplicatesFromSortedArray.java .
cp ~/epi/java/SpreadsheetEncoding.java .
cp ~/epi/java/ReverseLinkedListIterative.java .
cp ~/epi/java/RPN.java .
cp ~/epi/java/CircularQueue.java .
cp ~/epi/java/PathSumBinaryTree.java .
cp ~/epi/java/ClosestStars.java .
cp ~/epi/java/SquareRootInt.java .
cp ~/epi/java/Anagrams.java .
cp ~/epi/java/UnionIntervals.java .
cp ~/epi/java/SearchBSTForFirstOccurrenceRecursive.java .
cp ~/epi/java/SudokuSolve.java .
cp ~/epi/java/GassingUp.java .
cp ~/epi/java/Combinations.java .
cp ~/epi/java/TransformStringToOther.java .
cp ~/epi/java/FirstMissingPositive.java .
cp ~/epi/java/ViewFromAbove.java .
